# This workflow will install Python dependencies, the supported rail packages, and run the create_interactive_structure.py script
# If it fails with exit code = 2, that means that there have been updates to any of the stages 
# this usually means that you just need to create a new branch, run create_interactive_structure.py and do a PR with rail_base to update the .pyi 
# stub files 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Running create_interactive_structure script

on:
  schedule:
    - cron: 30 5 1 * *

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: System deps (MPI + build)
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential libbz2-dev \
        openmpi-bin libopenmpi-dev
    - name: Install dependencies
      run: |
        # sudo apt-get update
        # python -m pip install --upgrade pip
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install "numpy<2" cython
        python -m pip install --upgrade --no-binary=mpi4py mpi4py
        python -m pip install --no-build-isolation somoclu
        python -m pip install --upgrade pip
        pip install wheel numpy
        pip install .
        pip install .[dev]
        pip install .[algos]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # runs the create interactive structure test to see if the interactive structure needs to be changed
    # returns a 1 if something went wrong with the script, or a 2 if the files need to be changed
    - name: Run create_interactive_structure.py 
      run: | 
        python create_interactive_structure.py
    - name: Send status to Slack app (RAIL CI Reporter)
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.repository }} create_interactive_structure workflow"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: *${{ job.status }}* :${{ job.status }}: \nWhen exit code = 2, this means you need to run create_interactive_structure.py, <https://rail-hub.readthedocs.io/en/latest/source/development/contribute_to_rail.html#merge|see details here>"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
